### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by ElimeletCA** [SamuEDL/Tools_T8100#1]
@SamuEDL Saludos, probe la rom mediante flashboot en una tablet similar y se instalo perfecto pero no tengo ni touchscreen ni wifi, hay forma de montar los drivers en el .img antes de instalarlo mediante flashboot?

**Comment by SamuEDL** [comment]
Buenos días
Si te soy sincero no se si tendrá solución. Ya que el problema seria encontrar un driver que funcione con tu pantalla táctil. ¿Que modelo de tablet tienes? ¿Y el tactil no funciona totalmente o esta mal mapeado?

**Comment by ElimeletCA** [comment]
Saludos, agradecido de tu respuesta es una RVPVK808, el touchscreen no funciona en lo absoluto, aun no logro identificar el modelo del driver pero te adjunto imagenes de la placa, realmente ni siquiera me interesa el wifi, si solo obtengo touchscreen estaria bien porque mi plan es usarla como ebook, he navegado en los rincones de internet y un monton de paginas chinas, pero nada, espero me puedas ayudar con este caso
https://1drv.ms/b/s!ApBT3CBr_cLtgVilHoVsinoRtQB0?e=uljzOR

**Comment by SamuEDL** [comment]
En principio, mirando por encima la placa base en características se asemeja mas con las teclast P80. Ya que ambos llevan un allwinner A133 y comparten Wifi (AW859A). Así que a lo mejor pueda funcionar en tu tablet. 

Eso si, el táctil en este caso no te puedo confirmar que pueda funcionar, ya que no puedo llegar a ver que panel tactil tiene tu tablet al no haber ninguna referencia.

----------------------------

El firmware de la teclast P80, lo puedes descargar de la pagina del fabricante, poniendo "G3M2" en su buscador: https://www.teclast.com/en/firmware/

Y puedes desampaquetar el .img con imgrepacker, para posteriormente flashearlo mediante fastboot: https://forum.xda-developers.com/t/tool-imgrepacker-livesuits-phoenixsuits-firmware-images-unpacker-packer.1753473/

Eso si, te recomendaría usar el procedimiento del fastboot, pero solo flashear los ficheros boot.img y super.img. Ya que si usas el procedimiento de flashear por defecto de alllwinner, puede que machaque los ficheros que llevan la configuración de la pantalla (TOC1.img y TOC2.img) y deje de dar imagen en caso de que use otro LCD.

**Comment by ElimeletCA** [comment]
Muchas gracias, ya la monte, sigue sin funcionar el touchscreen pero me funciona hasta el wifi y la camara que no funcionaban, probe la V1.03, podria probar la V1.04 pero no creo que haga una diferencia, pero supongo que es lo mejor que obtendre en este caso, conoces algun otro modelo similar por si acaso?

UPDATE: Ya tengo el modelo del touchscreen, es este RP2319-FPC-V1.0 y el controlador es silead gsl1680

Depure un poco con Zeus Toolkit, el firmware esta cargando el gslX680new
Module                  Size  Used by
gslX680new           4399104  0 

Probe abrir el firmware de teclast con Dragonface para reemplazarlo por el gsl1680.ko pero no quiso abrirlo, obtengo "Firmware does not support the tools to modify, make sure that the firmware version", es una buena noticia ya que creo estoy acercandome a solucionarlo pero aqui vuelvo a atascarme.

**Comment by SamuEDL** [comment]
Buenas, me alegro que hayas podido avanzar algo. Para modificar el super.img podrías seguir esta guía: https://forum.xda-developers.com/t/editing-system-img-inside-super-img-and-flashing-our-modifications.4196625/

Eso si, en vez de desempaquetar el system.img que hay en el interior del super.img. Desempaqueta el vendor.img, que es donde se alojan las librerías de la tablet a partir de android 10. 

Por cierto, el vendor.img lo puedes flashear desde el modo fastbootd, por lo que no hace falta que empaquetes todo renuevo.

-----------------------

Voy haber si encuentro alguna otra rom compatible, pero ya el resto de dispositivos que conozco usan android 11 y posteriores. Y cambia la estructura de particiones y el kernel por lo que sus librerias no son compatibles.

**Igualmente si quieres echar un vistazo a estas tablets son:**
- Q-Link Scepter 8 (Gen1 (Allwinner A100/Android 11) y Gen 2 (Allwinner A133/Android 12): https://forum.xda-developers.com/t/guide-firmware-qlink-scepter-8-gen-1-gen-2-factory-firmware-restoration-upgrading-guide.4412585/
- Teclast P85 "G3K5" (Allwinner A133/Android 11)

**Comment by ElimeletCA** [comment]
Gracias, perdona si estoy molestando mucho, ya logre modificar el vendor con el nuevo driver pero usando el mismo nombre del anterior, todo bien hasta ahi pero al momento de flashear obtengo la siguiente salida
![image](https://github.com/SamuEDL/Tools_T8100/assets/138534856/506345c9-9cde-425b-aa3b-a089a0b4c3de)
Probe a flasher el vendor sin ningun cambio y lo mismo, no se si estoy obviando algun al momento de flashear, si hay que borrarla antes de, etc, simplemente coloco la tablet en fastbootd y ejecuto el comando inmediatamente. PD: Si pruebo a flashear por ejemplo boot.img nuevamente lo hace sin problemas

**Comment by SamuEDL** [comment]
Nada no te preocupes, no molestas para nada. A lo mejor lo estas intentando instalar en modo fastboot/bootloader y no en fastbootd. En el modo fastbootd tiene esta interfaz la tablet:

![imagen](https://github.com/SamuEDL/Tools_T8100/assets/59443298/e509d47b-2851-4080-8765-362e10556ee1)

**Comment by ElimeletCA** [comment]
Si, estoy en esa interfaz, como te dije si intento flashear boot o super nuevamente funcionan sin problemas, se me ocurrió que debo borrar vendor y luego crearla nuevamente para flashearla ya que vendor me aparece como una partición lógica pero no se, solo hago suposiciones

**Comment by SamuEDL** [comment]
Ni idea que puede ser. Si eso intenta empaquetarlo en un system.img como indica la guia, para ver si asi te deja flashearlo.

**Comment by ElimeletCA** [comment]
Ya probé a trabajar fastboot desde Ubuntu directamente y ya flasheo pero no funcionó el driver sin embargo ya se que debo enfocarme en encontrar el driver correcto y tarde o temprano lo soluciono, muchimas gracias por la ayuda
